- name: install packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - dnsutils
      - nmap
      - tcpdump
      - wireshark-qt

- name: add wireshark group
  group:
    name: wireshark
    state: present

- name: add pi user to wireshark group
  user:
    name: pi
    groups: wireshark
    append: yes

- name: configure non-root wireshark access
  debconf:
    name: wireshark-common
    question: wireshark-common/install-setuid
    value: yes
    vtype: boolean
