- name: install packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - dnsmasq

- name: enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: install lan0 config
  copy:
    dest: /etc/systemd/network/lan0.network
    src: lan0.network
    mode: 0644
  register: network_config

- name: restart networking
  service:
    name: systemd-networkd
    state: restarted
    enabled: yes
  when: network_config.changed

- name: install dnsmasq config
  copy:
    dest: /etc/dnsmasq.d/pi-network-lab.conf
    src: dnsmasq.conf
    mode: 0644
  register: dnsmasq_config

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
    enabled: yes
  when: dnsmasq_config.changed or network_config.changed
